[project]
name = "rl-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[toy-text]>=1.2.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "tqdm>=4.67.1",
]
